//go:build !proto

// Code generated by proto generation — DO NOT EDIT manually.
// Run `make proto` to regenerate from pkg/proto/payment.proto.
//
// This stub satisfies the Go toolchain before proto generation is run.
// After running `make proto`, this file is replaced by the real generated output.

package pb

import (
	"context"
	"strings"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// Suppress unused import warnings in stub
var _ = codes.OK
var _ = status.Error
var _ = protoimpl.UnsafeEnabled
var _ *timestamppb.Timestamp

// ── Proto Extensions (for auth interceptor) ───────────────────────────────────

// Action enum mirrors the permission action values in the proto spec.
type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_CREATE      Action = 1
	Action_ACTION_READ        Action = 2
	Action_ACTION_UPDATE      Action = 4
	Action_ACTION_DELETE      Action = 8
)

func (a Action) Number() protoreflect.EnumNumber { return protoreflect.EnumNumber(a) }

// GetResourceExtension extracts the "permission.resource" proto extension value
// from a method's options. In the stub (before proto generation), always returns "".
// After `make proto`, this reads the actual proto extension.
func GetResourceExtension(m proto.Message) string {
	return ""
}

// GetActionExtension extracts the "permission.action" proto extension value
// from a method's options. In the stub (before proto generation), always returns zero.
func GetActionExtension(m proto.Message) Action {
	return Action_ACTION_UNSPECIFIED
}

// ── Enums ────────────────────────────────────────────────────────────────────

type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED Provider = 0
	Provider_PROVIDER_CUSTOM      Provider = 4
	Provider_PROVIDER_DANA        Provider = 5
	Provider_PROVIDER_XENDIT      Provider = 6
	Provider_PROVIDER_KOMOJU      Provider = 7
)

func (p Provider) String() string {
	switch p {
	case Provider_PROVIDER_CUSTOM:
		return "PROVIDER_CUSTOM"
	case Provider_PROVIDER_DANA:
		return "dana"
	case Provider_PROVIDER_XENDIT:
		return "xendit"
	case Provider_PROVIDER_KOMOJU:
		return "komoju"
	default:
		return "PROVIDER_UNSPECIFIED"
	}
}

func (p Provider) MarshalJSON() ([]byte, error) {
	return []byte(`"` + p.String() + `"`), nil
}

func (p *Provider) UnmarshalJSON(b []byte) error {
	s := strings.Trim(string(b), `"`)
	switch s {
	case "PROVIDER_CUSTOM", "4":
		*p = Provider_PROVIDER_CUSTOM
	case "PROVIDER_DANA", "5":
		*p = Provider_PROVIDER_DANA
	case "PROVIDER_XENDIT", "6":
		*p = Provider_PROVIDER_XENDIT
	case "PROVIDER_KOMOJU", "7":
		*p = Provider_PROVIDER_KOMOJU
	default:
		*p = Provider_PROVIDER_UNSPECIFIED
	}
	return nil
}

type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	TransactionStatus_PENDING                        TransactionStatus = 1
	TransactionStatus_FULFILLING                     TransactionStatus = 2
	TransactionStatus_FULFILLED                      TransactionStatus = 3
	TransactionStatus_FAILED                         TransactionStatus = 4
	TransactionStatus_CANCELED                       TransactionStatus = 5
	TransactionStatus_EXPIRED                        TransactionStatus = 6
)

func (s TransactionStatus) String() string {
	switch s {
	case TransactionStatus_PENDING:
		return "PENDING"
	case TransactionStatus_FULFILLING:
		return "FULFILLING"
	case TransactionStatus_FULFILLED:
		return "FULFILLED"
	case TransactionStatus_FAILED:
		return "FAILED"
	case TransactionStatus_CANCELED:
		return "CANCELED"
	case TransactionStatus_EXPIRED:
		return "EXPIRED"
	default:
		return "TRANSACTION_STATUS_UNSPECIFIED"
	}
}

func (s TransactionStatus) MarshalJSON() ([]byte, error) {
	return []byte(`"` + s.String() + `"`), nil
}

func (s *TransactionStatus) UnmarshalJSON(b []byte) error {
	str := strings.Trim(string(b), `"`)
	switch str {
	case "PENDING", "1":
		*s = TransactionStatus_PENDING
	case "FULFILLING", "2":
		*s = TransactionStatus_FULFILLING
	case "FULFILLED", "3":
		*s = TransactionStatus_FULFILLED
	case "FAILED", "4":
		*s = TransactionStatus_FAILED
	case "CANCELED", "5":
		*s = TransactionStatus_CANCELED
	case "EXPIRED", "6":
		*s = TransactionStatus_EXPIRED
	default:
		*s = TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
	}
	return nil
}

// ── Messages ─────────────────────────────────────────────────────────────────

type CreatePaymentIntentRequest struct {
	Provider           Provider `protobuf:"varint,1,opt,name=provider,proto3,enum=payment.v1.Provider" json:"provider,omitempty"`
	ItemId             string   `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"itemId,omitempty"`
	Quantity           int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Description        string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ClientOrderId      string   `protobuf:"bytes,5,opt,name=client_order_id,json=clientOrderId,proto3" json:"clientOrderId,omitempty"`
	CustomProviderName string   `protobuf:"bytes,6,opt,name=custom_provider_name,json=customProviderName,proto3" json:"customProviderName,omitempty"`
	RegionCode         string   `protobuf:"bytes,7,opt,name=region_code,json=regionCode,proto3" json:"regionCode,omitempty"`
}

func (x *CreatePaymentIntentRequest) Reset()         {}
func (x *CreatePaymentIntentRequest) String() string { return x.ItemId }
func (x *CreatePaymentIntentRequest) ProtoMessage()  {}

type CreatePaymentIntentResponse struct {
	TransactionId string            `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transactionId,omitempty"`
	PaymentUrl    string            `protobuf:"bytes,2,opt,name=payment_url,json=paymentUrl,proto3" json:"paymentUrl,omitempty"`
	QrCodeData    string            `protobuf:"bytes,3,opt,name=qr_code_data,json=qrCodeData,proto3" json:"qrCodeData,omitempty"`
	ExpiresAt     string            `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expiresAt,omitempty"`
	Status        TransactionStatus `protobuf:"varint,5,opt,name=status,proto3,enum=payment.v1.TransactionStatus" json:"status,omitempty"`
}

func (x *CreatePaymentIntentResponse) Reset()         {}
func (x *CreatePaymentIntentResponse) String() string { return x.TransactionId }
func (x *CreatePaymentIntentResponse) ProtoMessage()  {}

type GetTransactionRequest struct {
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transactionId,omitempty"`
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *GetTransactionRequest) Reset()         {}
func (x *GetTransactionRequest) String() string { return x.TransactionId }
func (x *GetTransactionRequest) ProtoMessage()  {}

type TransactionResponse struct {
	TransactionId       string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transactionId,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"userId,omitempty"`
	Namespace           string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Provider            Provider               `protobuf:"varint,4,opt,name=provider,proto3,enum=payment.v1.Provider" json:"provider,omitempty"`
	Amount              int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ItemId              string                 `protobuf:"bytes,6,opt,name=item_id,json=itemId,proto3" json:"itemId,omitempty"`
	Quantity            int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Status              TransactionStatus      `protobuf:"varint,8,opt,name=status,proto3,enum=payment.v1.TransactionStatus" json:"status,omitempty"`
	ProviderStatus      string                 `protobuf:"bytes,9,opt,name=provider_status,json=providerStatus,proto3" json:"providerStatus,omitempty"`
	ProviderTxId        string                 `protobuf:"bytes,10,opt,name=provider_tx_id,json=providerTxId,proto3" json:"providerTxId,omitempty"`
	FailureReason       string                 `protobuf:"bytes,11,opt,name=failure_reason,json=failureReason,proto3" json:"failureReason,omitempty"`
	RefundStatus        string                 `protobuf:"bytes,12,opt,name=refund_status,json=refundStatus,proto3" json:"refundStatus,omitempty"`
	CustomProviderName  string                 `protobuf:"bytes,13,opt,name=custom_provider_name,json=customProviderName,proto3" json:"customProviderName,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty"`
	ExpiresAt           *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=expires_at,json=expiresAt,proto3" json:"expiresAt,omitempty"`
	ItemName            string                 `protobuf:"bytes,16,opt,name=item_name,json=itemName,proto3" json:"itemName,omitempty"`
	CurrencyCode        string                 `protobuf:"bytes,17,opt,name=currency_code,json=currencyCode,proto3" json:"currencyCode,omitempty"`
	PaymentUrl          string                 `protobuf:"bytes,18,opt,name=payment_url,json=paymentUrl,proto3" json:"paymentUrl,omitempty"`
	RefundReason        string                 `protobuf:"bytes,19,opt,name=refund_reason,json=refundReason,proto3" json:"refundReason,omitempty"`
	RefundFailureReason string                 `protobuf:"bytes,20,opt,name=refund_failure_reason,json=refundFailureReason,proto3" json:"refundFailureReason,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *TransactionResponse) Reset()         {}
func (x *TransactionResponse) String() string { return x.TransactionId }
func (x *TransactionResponse) ProtoMessage()  {}

type WebhookRequest struct {
	ProviderName string            `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"providerName,omitempty"`
	RawPayload   []byte            `protobuf:"bytes,2,opt,name=raw_payload,json=rawPayload,proto3" json:"rawPayload,omitempty"`
	Headers      map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *WebhookRequest) Reset()         {}
func (x *WebhookRequest) String() string { return x.ProviderName }
func (x *WebhookRequest) ProtoMessage()  {}

type WebhookResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WebhookResponse) Reset()         {}
func (x *WebhookResponse) String() string { return x.Message }
func (x *WebhookResponse) ProtoMessage()  {}

type ListTransactionsRequest struct {
	Namespace    string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	UserId       string            `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"userId,omitempty"`
	StatusFilter TransactionStatus `protobuf:"varint,3,opt,name=status_filter,json=statusFilter,proto3,enum=payment.v1.TransactionStatus" json:"statusFilter,omitempty"`
	Provider     string            `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	PageSize     int32             `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"pageSize,omitempty"`
	Cursor       string            `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Search       string            `protobuf:"bytes,7,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *ListTransactionsRequest) Reset()         {}
func (x *ListTransactionsRequest) String() string { return x.Namespace }
func (x *ListTransactionsRequest) ProtoMessage()  {}

type ListTransactionsResponse struct {
	Transactions []*TransactionResponse `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	NextCursor   string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"nextCursor,omitempty"`
}

func (x *ListTransactionsResponse) Reset()         {}
func (x *ListTransactionsResponse) String() string { return "" }
func (x *ListTransactionsResponse) ProtoMessage()  {}

type RefundRequest struct {
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transactionId,omitempty"`
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Namespace     string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *RefundRequest) Reset()         {}
func (x *RefundRequest) String() string { return x.TransactionId }
func (x *RefundRequest) ProtoMessage()  {}

type RefundResponse struct {
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transactionId,omitempty"`
	Success       bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RefundResponse) Reset()         {}
func (x *RefundResponse) String() string { return x.TransactionId }
func (x *RefundResponse) ProtoMessage()  {}

type SyncTransactionRequest struct {
	Namespace     string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TransactionId string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transactionId,omitempty"`
}

func (x *SyncTransactionRequest) Reset()         {}
func (x *SyncTransactionRequest) String() string { return x.TransactionId }
func (x *SyncTransactionRequest) ProtoMessage()  {}

type SyncTransactionsRequest struct {
	Namespace    string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Provider     string            `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	StatusFilter TransactionStatus `protobuf:"varint,3,opt,name=status_filter,json=statusFilter,proto3,enum=payment.v1.TransactionStatus" json:"statusFilter,omitempty"`
	PageSize     int32             `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"pageSize,omitempty"`
	Cursor       string            `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
}

func (x *SyncTransactionsRequest) Reset()         {}
func (x *SyncTransactionsRequest) String() string { return x.Namespace }
func (x *SyncTransactionsRequest) ProtoMessage()  {}

type SyncTransactionResult struct {
	TransactionId      string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transactionId,omitempty"`
	Provider           string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderTxId       string `protobuf:"bytes,3,opt,name=provider_tx_id,json=providerTxId,proto3" json:"providerTxId,omitempty"`
	PaymentStatus      string `protobuf:"bytes,4,opt,name=payment_status,json=paymentStatus,proto3" json:"paymentStatus,omitempty"`
	RefundStatus       string `protobuf:"bytes,5,opt,name=refund_status,json=refundStatus,proto3" json:"refundStatus,omitempty"`
	RawPaymentStatus   string `protobuf:"bytes,6,opt,name=raw_payment_status,json=rawPaymentStatus,proto3" json:"rawPaymentStatus,omitempty"`
	RawRefundStatus    string `protobuf:"bytes,7,opt,name=raw_refund_status,json=rawRefundStatus,proto3" json:"rawRefundStatus,omitempty"`
	RefundAmount       int64  `protobuf:"varint,8,opt,name=refund_amount,json=refundAmount,proto3" json:"refundAmount,omitempty"`
	RefundCurrencyCode string `protobuf:"bytes,9,opt,name=refund_currency_code,json=refundCurrencyCode,proto3" json:"refundCurrencyCode,omitempty"`
	Outcome            string `protobuf:"bytes,10,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Message            string `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SyncTransactionResult) Reset()         {}
func (x *SyncTransactionResult) String() string { return x.TransactionId }
func (x *SyncTransactionResult) ProtoMessage()  {}

type SyncTransactionResponse struct {
	Result *SyncTransactionResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SyncTransactionResponse) Reset()         {}
func (x *SyncTransactionResponse) String() string { return "" }
func (x *SyncTransactionResponse) ProtoMessage()  {}

type SyncTransactionsResponse struct {
	Results    []*SyncTransactionResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results"`
	NextCursor string                   `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"nextCursor"`
}

func (x *SyncTransactionsResponse) Reset()         {}
func (x *SyncTransactionsResponse) String() string { return "" }
func (x *SyncTransactionsResponse) ProtoMessage()  {}

type PublicSyncTransactionRequest struct {
	Namespace     string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TransactionId string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transactionId,omitempty"`
}

func (x *PublicSyncTransactionRequest) Reset()         {}
func (x *PublicSyncTransactionRequest) String() string { return x.TransactionId }
func (x *PublicSyncTransactionRequest) ProtoMessage()  {}

type PublicSyncTransactionsRequest struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Provider  string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	PageSize  int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"pageSize,omitempty"`
	Cursor    string `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
}

func (x *PublicSyncTransactionsRequest) Reset()         {}
func (x *PublicSyncTransactionsRequest) String() string { return x.Namespace }
func (x *PublicSyncTransactionsRequest) ProtoMessage()  {}

type CancelTransactionRequest struct {
	Namespace     string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TransactionId string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transactionId,omitempty"`
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *CancelTransactionRequest) Reset()         {}
func (x *CancelTransactionRequest) String() string { return x.TransactionId }
func (x *CancelTransactionRequest) ProtoMessage()  {}

type CancelTransactionResponse struct {
	TransactionId string               `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transactionId,omitempty"`
	Success       bool                 `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Transaction   *TransactionResponse `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Message       string               `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CancelTransactionResponse) Reset()         {}
func (x *CancelTransactionResponse) String() string { return x.TransactionId }
func (x *CancelTransactionResponse) ProtoMessage()  {}

// ── Server Interfaces ─────────────────────────────────────────────────────────

type PaymentServiceServer interface {
	CreatePaymentIntent(context.Context, *CreatePaymentIntentRequest) (*CreatePaymentIntentResponse, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*TransactionResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CreatePaymentIntent(context.Context, *CreatePaymentIntentRequest) (*CreatePaymentIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePaymentIntent not implemented")
}
func (UnimplementedPaymentServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}

type PublicServiceServer interface {
	SyncMyTransaction(context.Context, *PublicSyncTransactionRequest) (*SyncTransactionResponse, error)
	SyncMyTransactions(context.Context, *PublicSyncTransactionsRequest) (*SyncTransactionsResponse, error)
	CancelMyTransaction(context.Context, *CancelTransactionRequest) (*CancelTransactionResponse, error)
	mustEmbedUnimplementedPublicServiceServer()
}

type UnimplementedPublicServiceServer struct{}

func (UnimplementedPublicServiceServer) SyncMyTransaction(context.Context, *PublicSyncTransactionRequest) (*SyncTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncMyTransaction not implemented")
}
func (UnimplementedPublicServiceServer) SyncMyTransactions(context.Context, *PublicSyncTransactionsRequest) (*SyncTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncMyTransactions not implemented")
}
func (UnimplementedPublicServiceServer) CancelMyTransaction(context.Context, *CancelTransactionRequest) (*CancelTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelMyTransaction not implemented")
}
func (UnimplementedPublicServiceServer) mustEmbedUnimplementedPublicServiceServer() {}

type WebhookServiceServer interface {
	HandleWebhook(context.Context, *WebhookRequest) (*WebhookResponse, error)
	mustEmbedUnimplementedWebhookServiceServer()
}

type UnimplementedWebhookServiceServer struct{}

func (UnimplementedWebhookServiceServer) HandleWebhook(context.Context, *WebhookRequest) (*WebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleWebhook not implemented")
}
func (UnimplementedWebhookServiceServer) mustEmbedUnimplementedWebhookServiceServer() {}

type AdminServiceServer interface {
	ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error)
	GetTransactionDetail(context.Context, *GetTransactionRequest) (*TransactionResponse, error)
	Refund(context.Context, *RefundRequest) (*RefundResponse, error)
	SyncTransaction(context.Context, *SyncTransactionRequest) (*SyncTransactionResponse, error)
	SyncTransactions(context.Context, *SyncTransactionsRequest) (*SyncTransactionsResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedAdminServiceServer) GetTransactionDetail(context.Context, *GetTransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionDetail not implemented")
}
func (UnimplementedAdminServiceServer) Refund(context.Context, *RefundRequest) (*RefundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refund not implemented")
}
func (UnimplementedAdminServiceServer) SyncTransaction(context.Context, *SyncTransactionRequest) (*SyncTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncTransaction not implemented")
}
func (UnimplementedAdminServiceServer) SyncTransactions(context.Context, *SyncTransactionsRequest) (*SyncTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncTransactions not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}

// ── gRPC Registration ─────────────────────────────────────────────────────────

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func RegisterPublicServiceServer(s grpc.ServiceRegistrar, srv PublicServiceServer) {
	s.RegisterService(&PublicService_ServiceDesc, srv)
}

func RegisterWebhookServiceServer(s grpc.ServiceRegistrar, srv WebhookServiceServer) {
	s.RegisterService(&WebhookService_ServiceDesc, srv)
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "CreatePaymentIntent", Handler: _PaymentService_CreatePaymentIntent_Handler},
		{MethodName: "GetTransaction", Handler: _PaymentService_GetTransaction_Handler},
	},
}

var PublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.PublicService",
	HandlerType: (*PublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "SyncMyTransaction", Handler: _PublicService_SyncMyTransaction_Handler},
		{MethodName: "SyncMyTransactions", Handler: _PublicService_SyncMyTransactions_Handler},
		{MethodName: "CancelMyTransaction", Handler: _PublicService_CancelMyTransaction_Handler},
	},
}

var WebhookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.WebhookService",
	HandlerType: (*WebhookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "HandleWebhook", Handler: _WebhookService_HandleWebhook_Handler},
	},
}

var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "ListTransactions", Handler: _AdminService_ListTransactions_Handler},
		{MethodName: "GetTransactionDetail", Handler: _AdminService_GetTransactionDetail_Handler},
		{MethodName: "Refund", Handler: _AdminService_Refund_Handler},
		{MethodName: "SyncTransaction", Handler: _AdminService_SyncTransaction_Handler},
		{MethodName: "SyncTransactions", Handler: _AdminService_SyncTransactions_Handler},
	},
}

func _PaymentService_CreatePaymentIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreatePaymentIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/payment.v1.PaymentService/CreatePaymentIntent"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreatePaymentIntent(ctx, req.(*CreatePaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/payment.v1.PaymentService/GetTransaction"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_SyncMyTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicSyncTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).SyncMyTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/payment.v1.PublicService/SyncMyTransaction"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).SyncMyTransaction(ctx, req.(*PublicSyncTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_SyncMyTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicSyncTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).SyncMyTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/payment.v1.PublicService/SyncMyTransactions"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).SyncMyTransactions(ctx, req.(*PublicSyncTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_CancelMyTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).CancelMyTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/payment.v1.PublicService/CancelMyTransaction"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).CancelMyTransaction(ctx, req.(*CancelTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_HandleWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).HandleWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/payment.v1.WebhookService/HandleWebhook"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).HandleWebhook(ctx, req.(*WebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/payment.v1.AdminService/ListTransactions"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListTransactions(ctx, req.(*ListTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetTransactionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetTransactionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/payment.v1.AdminService/GetTransactionDetail"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetTransactionDetail(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/payment.v1.AdminService/Refund"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Refund(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SyncTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SyncTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/payment.v1.AdminService/SyncTransaction"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SyncTransaction(ctx, req.(*SyncTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SyncTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SyncTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/payment.v1.AdminService/SyncTransactions"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SyncTransactions(ctx, req.(*SyncTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ── gRPC-Gateway Registration stubs ──────────────────────────────────────────
// These are replaced by the real generated gateway code after `make proto`.

func RegisterPaymentServiceHandlerFromEndpoint(ctx context.Context, mux interface{}, endpoint string, opts []grpc.DialOption) error {
	return nil
}

func RegisterPublicServiceHandlerFromEndpoint(ctx context.Context, mux interface{}, endpoint string, opts []grpc.DialOption) error {
	return nil
}

func RegisterWebhookServiceHandlerFromEndpoint(ctx context.Context, mux interface{}, endpoint string, opts []grpc.DialOption) error {
	return nil
}

func RegisterAdminServiceHandlerFromEndpoint(ctx context.Context, mux interface{}, endpoint string, opts []grpc.DialOption) error {
	return nil
}
